import pygame as pg
import math


# def calculateResolution(scale=1):
#     """Calculates screen resolution for dynamic screen sizing"""
#     pg.init()
#     screen = pg.display.Info()
#     pg.quit()
#     return int(screen.current_w * scale), int(screen.current_h * scale)

# GAME SETTINGS
# MODES 3D, Test
# TESTMODES 2D, 3D
MODE = '3D'
TESTMODE = '3D'
LINEOFSIGHT = False

# SCREEN SETTINGS
RES = WIDTH, HEIGHT = 1600, 900
FPS = 60
HALFWIDTH = WIDTH // 2
HALFHEIGHT = HEIGHT // 2

# PLAYER MOVEMENT SETTINGS
PLAYER_POSITION = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROTATION_SPEED = 0.002
PLAYERSCALE = 60

# GAMEPLAY SETTINGS
#Mouse
ENABLE_MOUSE = True
DISABLE_MOUSE_VISIBILITY = True
MOUSESENTITIVITY = 0.00035
MOUSE_MAX_REL = 40
MOUSE_LEFT_BORDER = 100
MOUSE_RIGHT_BORDER = WIDTH - MOUSE_LEFT_BORDER

#Key Rotation
ENABLE_KEY_ROTATION = False

# PLAYER FIELD OF VIEW SETTINGS
FOV = math.pi / 3
HFOV = FOV / 2
RAYS = WIDTH // 2
HRAYS = RAYS // 2
ANGLECHANGE = FOV / RAYS
MAX_DEPTH = 20
SCREENDISTANCE = HALFWIDTH / math.tan(HFOV)
SCALE = WIDTH // RAYS

# GRAPHIC SETTINGS
TEXTURESIZE = 256
HALFTEXTURESIZE = TEXTURESIZE // 2
